# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql2
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  # database: appi
  database: itmgmt
  # database: homes
  # database: 4mstech
  pool: 10
  username: root
  password:
  socket: /tmp/mysql.sock



# development:
#   adapter: postgresql
#   encoding: unicode
#   database: magno
#   pool: 5
#   username: myapp
#   password: password1


instant:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: instantvoice
  pool: 5
  username: brq-infra
  password: brq@infra
  host: 10.3.57.100
  port: 3306
# 

#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
telefonia:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: telefonia
  pool: 10
  username: root
  password:
  socket: /tmp/mysql.sock


rm:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rm
  pool: 10
  username: root
  password:
  socket: /tmp/mysql.sock

ura:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: brq
  pool: 5
  username: brqura
  password: brqpassword
  host: sp.iv.brq.com


# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: appi
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tasklist_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
