# development:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: itmgmt #Instant
#   pool: 10
#   username: root
#   password: 
#   host: 127.0.0.1
#   port: 3306 # porta do mapeamento docker

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: itmgmt #Instant
  pool: 10
  username: root
  password: sWEll1620
  host: 127.0.0.1
  port: 3307 # porta do mapeamento docker

instant:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: instantvoice
  pool: 5
  username: root
  password: 
  host: 127.0.0.1
  port: 3306
# 

#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
telefonia:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: telefonia
  pool: 10
  username: root
  password:
  socket: /tmp/mysql.sock


rm:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rm
  pool: 10
  username: root
  password:
  socket: /tmp/mysql.sock

ura:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: brq
  pool: 5
  username: root
  password: 
  host: 127.0.0.1


# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# # Do not set this db to the same as development or production.
# test:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: itmgmt
#   pool: 10
#   username: root
#   password:
#   socket: /tmp/mysql.sock

# production:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: itmgmt
#   # database: 4mstech
#   pool: 10
#   username: root
#   password:
#   socket: /tmp/mysql.sock

