development:
   hidden_features: "alertas help"
   smtp:
     address: "smtp.gmail.com"
     port: 587
     user_name: "zemagno@gmail.com"
     password: "Mmp1bk!!1"
     authentication: 'plain'
     enable_starttls_auto: true
   mail:
     domain: "@3misas.com"
     separator: ";"
     default_from: "zemagno@gmail.com"
   jira:
     url: "jiracorp.brq.com"
     username: "magno"
     password: "Jcmnkl##3"
     context_path: ""
     use_ssl: false 
     auth_type: :basic 

production:
   foo:
     bar: "blah blah"
     baz: "blah blah"
     qux: "blah blah"

test:
   foo:
     bar: "blah blah"
     baz: "blah blah"
     qux: "blah blah"