# Encoding: utf-8
begin
  tipoci = Tipoci.create({:tipo => "Contrato"})
  tipoci.dicdados.create({nome: "Status",tipoci_id: tipoci.id,ordem: "",url: "",descricao: "",valores: "Pendente Assinatura,Enviado Fornecedor e Aguardando via BRQ,Armazenado,Inexistente",apelido: "status",tipo: "",regex: "",mandatorio: "false",tooltip: "",comentarios: "NAO ALTERAR os valores acima, pois eles sao usados hardcoded em relatorios."})
  tipoci.dicdados.create({nome: "Numero Contrato",tipoci_id: tipoci.id,ordem: "1",url: "",descricao: "",valores: "",apelido: "numerocontrato",tipo: "",regex: "",mandatorio: "",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Tipo Contrato",tipoci_id: tipoci.id,ordem: "10",url: "",descricao: "",valores: ",Bebidas,Correios,Email,Hardware,Impressao,Insumos descartáveis,Internet,Limpeza,Link,Locacao,Locacao Imovel,Manutencao,Micro,Seguranca,Seguro Predial,Software,Telefonia,Nuvem",apelido: "TipoContrato",tipo: "",regex: "",mandatorio: "false",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Indice Reajuste",tipoci_id: tipoci.id,ordem: "20",url: "",descricao: "",valores: ",Classe,IGP-M,IGM-DI,IPC,Sem Indice Definido",apelido: "indicereajuste",tipo: "",regex: "",mandatorio: "false",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Mes Reajuste",tipoci_id: tipoci.id,ordem: "21",url: "",descricao: "",valores: " ,1,2,3,4,5,6,7,8,9,10,11,12",apelido: "mesreajuste",tipo: "",regex: "",mandatorio: "false",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Data de Inicio",tipoci_id: tipoci.id,ordem: "30",url: "",descricao: "DD/MM/AAAA",valores: "",apelido: "datainicio",tipo: "",regex: "(0[1-9]|[12][0-9]|3[01])\/(0[1-9]|1[012])\/20\d\d",mandatorio: "false",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Data Fim",tipoci_id: tipoci.id,ordem: "31",url: "",descricao: "DD/MM/AAAA",valores: "",apelido: "vencimentocontrato",tipo: "",regex: "(0[1-9]|[12][0-9]|3[01])\/(0[1-9]|1[012])\/20\d\d",mandatorio: "false",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Data Renovacao",tipoci_id: tipoci.id,ordem: "32",url: "",descricao: "DD/MM/AAAA",valores: "",apelido: "datarenovacao",tipo: "",regex: "(0[1-9]|[12][0-9]|3[01])\/(0[1-9]|1[012])\/20\d\d",mandatorio: "false",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Multa",tipoci_id: tipoci.id,ordem: "33",url: "",descricao: "Condicoes Gerais",valores: "",apelido: "multa",tipo: "",regex: "",mandatorio: "false",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Classificacao",tipoci_id: tipoci.id,ordem: "40",url: "",descricao: "",valores: "",apelido: "classificacao",tipo: "",regex: "",mandatorio: "",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Fornecedor",tipoci_id: tipoci.id,ordem: "100",url: "",descricao: "",valores: ",A2Brasil,Adobe,AirTech,Alctel,Algar,Allen,Apple,ArClima,Asana,Becker,Better,BrasilToner,Bruno Maciel,C&GCafe,Casa Limpa,CM Comandos,Citrix,Claro,Clap,Clean Service,Columbia,Copel,Correios,Criarenet,DDcom,Desk Manager,EcoRio,Embratel,Estuario,Executive Office,FMO,Garage Inn,GePark,Geracom,GVT,Goldtronic,Google,Hotlink,IBM,Indiana,Instant Solutions,IT Alliance,Iron Mountain,Jira,Kimberly,Klemart,Level3,Liberty,Liderox,Loginsis,Master Terceirizacao,Megatelecom,Microsoft,MontFrio,Motorsoft,Mundivox,Network Solutions,NKA,Obenicio,Oi,NilFrio,PNP,Produserv,Prolim,Real Protect,Registro BR,Ricoh,Royal,Salute,Sanidad,Servlar,Sigma,Softek,SoftwareOne,Sophos,Soservi,StarSoft,Survey Monkey,Symantec,Tecnoserv,TecTreina,Termitek,TIM,Tesa,Totalcad,Totvs,Verzzon,Vivo,XSolutions,Zero Grau",apelido: "fornecedor",tipo: "",regex: "",mandatorio: "false",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Incluir no Orcamento",tipoci_id: tipoci.id,ordem: "100",url: "",descricao: "",valores: "NAO,Incluir Orcamento",apelido: "incluirorcamento",tipo: "",regex: "",mandatorio: "false",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Observacao",tipoci_id: tipoci.id,ordem: "1000",url: "",descricao: "",valores: "",apelido: "observacao",tipo: "",regex: "",mandatorio: "false",tooltip: "",comentarios: ""})
rescue
end
tipoci = Tipoci.find_by_tipo("Contrato")
