# Encoding: utf-8
begin
  tipoci = Tipoci.create({:tipo => "Appliance"})
  tipoci.dicdados.create({nome: "Tipo Equipamento",tipoci_id: tipoci.id,ordem: "",url: "",descricao: "",valores: ",Ar Condicionado,Roteador,Rack,Media Gateway,TV,Video Conferencia,Access Point,AccWan,Library,Ata,Projetor,CFTV,NoBreak,Gerador,Outros",apelido: "tipoequipamento",tipo: "",regex: "",mandatorio: "true",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Fornecedor",tipoci_id: tipoci.id,ordem: "4",url: "%s",descricao: "",valores: "",apelido: "fornecedor",tipo: "",regex: "",mandatorio: "false",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Marca/Modelo",tipoci_id: tipoci.id,ordem: "5",url: "",descricao: "",valores: "",apelido: "marcamodelo",tipo: "",regex: "",mandatorio: "false",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Numero(s) de Serie",tipoci_id: tipoci.id,ordem: "6",url: "",descricao: "",valores: "",apelido: "numeroserie",tipo: "",regex: "",mandatorio: "false",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Caracteristicas/Capacidade",tipoci_id: tipoci.id,ordem: "7",url: "",descricao: "",valores: "",apelido: "caracteristicas",tipo: "",regex: "",mandatorio: "false",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Ativo",tipoci_id: tipoci.id,ordem: "10",url: "",descricao: "",valores: "",apelido: "ativo",tipo: "",regex: "\d{6}[a-zA-Z]{0,1}|N\/A",mandatorio: "false",tooltip: "Se o patrimonio tiver 5 digitos, coloque um zero na frente",comentarios: ""})
  tipoci.dicdados.create({nome: "SIP/MAC",tipoci_id: tipoci.id,ordem: "11",url: "",descricao: "",valores: "",apelido: "",tipo: "",regex: "",mandatorio: "",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "IP",tipoci_id: tipoci.id,ordem: "12",url: "",descricao: "",valores: "",apelido: "IP",tipo: "",regex: "",mandatorio: "",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Hostmonitor",tipoci_id: tipoci.id,ordem: "13",url: "",descricao: "",valores: " , Sim, Não",apelido: "",tipo: "",regex: "",mandatorio: "",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "CAPEX",tipoci_id: tipoci.id,ordem: "100",url: "",descricao: "Custo de Aquisicao",valores: "",apelido: "capex",tipo: "",regex: "",mandatorio: "",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "OPEX",tipoci_id: tipoci.id,ordem: "100",url: "",descricao: "Opex anual",valores: "",apelido: "opex",tipo: "",regex: "",mandatorio: "",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Tempo de Garantia/Contrato",tipoci_id: tipoci.id,ordem: "100",url: "",descricao: "DD/MM/AAAA",valores: "",apelido: "garantia",tipo: "",regex: "(0[1-9]|[12][0-9]|3[01])\/(0[1-9]|1[012])\/20\d\d",mandatorio: "false",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Vida Util",tipoci_id: tipoci.id,ordem: "100",url: "",descricao: "(em anos)",valores: "",apelido: "vidautil",tipo: "",regex: "",mandatorio: "",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Monitoracao",tipoci_id: tipoci.id,ordem: "100",url: "%s",descricao: "URL para monitoracao",valores: "",apelido: "",tipo: "",regex: "",mandatorio: "",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Contrato Manutencao Externa",tipoci_id: tipoci.id,ordem: "101",url: "",descricao: "",valores: " ,SIM,NAO",apelido: "contratomanutext",tipo: "",regex: "",mandatorio: "false",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Data Devol. Emprestimo ",tipoci_id: tipoci.id,ordem: "1001",url: "",descricao: " Data de devolução do emprestimo ",valores: "",apelido: "datadevolucaoEmprestimo",tipo: "",regex: "(0[1-9]|[12][0-9]|3[01])\/(0[1-9]|1[012])\/20\d\d",mandatorio: "false",tooltip: "",comentarios: "nao alterar apelido pois tem consulta que usa (fora email, relatorio)"})
  tipoci.dicdados.create({nome: "Data Compra",tipoci_id: tipoci.id,ordem: "1890",url: "",descricao: "",valores: "",apelido: "datacompra",tipo: "",regex: "(0[1-9]|[12][0-9]|3[01])\/(0[1-9]|1[012])\/20\d\d",mandatorio: "true",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Data Ultima Manutencao",tipoci_id: tipoci.id,ordem: "1990",url: "",descricao: "",valores: "",apelido: "dataultmanutencao",tipo: "",regex: "(0[1-9]|[12][0-9]|3[01])\/(0[1-9]|1[012])\/20\d\d",mandatorio: "true",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Data Prox Manutencao",tipoci_id: tipoci.id,ordem: "2000",url: "",descricao: "dd/mm/aaaa",valores: "",apelido: "dataproxmanut",tipo: "",regex: "(0[1-9]|[12][0-9]|3[01])\/(0[1-9]|1[012])\/20\d\d",mandatorio: "true",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Data Ultima Troca Bateria",tipoci_id: tipoci.id,ordem: "2050",url: "",descricao: "",valores: "",apelido: "dataulttrocabateria",tipo: "",regex: "(0[1-9]|[12][0-9]|3[01])\/(0[1-9]|1[012])\/20\d\d",mandatorio: "false",tooltip: "",comentarios: ""})
  tipoci.dicdados.create({nome: "Observacao",tipoci_id: tipoci.id,ordem: "3000",url: "",descricao: "",valores: "",apelido: "observacao",tipo: "",regex: "",mandatorio: "false",tooltip: "",comentarios: ""})
rescue
end
tipoci = Tipoci.find_by_tipo("Appliance")
